version: '3.4'

services:
  app:
    container_name: ro_php
    build: docker/php
    depends_on:
      - db
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/var/www/app
    working_dir: /var/www/app
    networks:
      - internal

  db:
    image: mysql:5.7.22
    container_name: ro_mysql
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: researcher_office
      MYSQL_ROOT_PASSWORD: symfony
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - internal

  webserver:
    container_name: ro_nginx
    image: nginx:alpine
    depends_on:
      - app
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8088:80
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  dbdata:
    driver: local
